---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: neutron-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgADsQziFlkwp1qrO+veeggsuYLORKqA87PixV5WWXhCta1E7xH/xAlIzgCVB1XciX1WEX1HGafFcmNON8kGWtr8/rygNWnzU9pqxwYhBfFpbBM42TuXRLTsM2RCCzgAmF/oStx0lGuTf6HIRyF5dZuC8+wk5Gltxq3xYYzybqsiip9c5HJskb84d8Nt8509OrLCl+vu5HYS72Q+rv/jTvJLfagtX4DtVtlQFeU5FL50AaIf0jiNscqKJd3UVcMhygOAmc7mQ7rPeB+zhq2V+LtMjB8HSYxNMLpiu13NBekSSzPJ1WBqUC5GrFwTTqIeLbZKrIxmdt2QldwNfbQ7iuBH+2+pXLoXD9H7eFX/XZTzr8xHXCD+/eJeha2Vw2qciC5kVonMtKhlNPrpau81hz/sMSXWZdmQWyL+Qlfu7BsIOaQMzNBxmWMdXscO7cduD1s0Q213AlvdctCIKfuPKNvFJCWw3GNRt4in9A0iwqU+Dr7n8cruL66n4mtQKT/simNKDXeNUnBAMeMTKY96EliTIHvHw1ifJSN38hqgtRVYiieX9Lt/kmb6U4GgVzunLPeUw+p2iwy5M0XuwU4xwXg3mQWFYSHFEqulsm4nCc8FH0Gi5kYI8LkTXIIS6S3h+HPKBEry+q0WHc70syBlH8QdsWG3zslfO+Zh+dkjGZd+CrL//FpjaMTkRgQDolhDaA+7w6NAvwRpxNzc5xXa4W+h2zBLJyBa1QFoYkz7DtfA1KYwAVVZwnHYNyi63Hk2XSnxw2bjkwcDWUL2v+wW2I+A
    username: AgCXqZ5O3h88+vPFqsf+r3psimGvBPsGDXHecENXembsBrTwRxkhU5zk790TTE9q8igF8uXP7HZsCX5Pa1PzAGV/9ZR0caHyCjHpHGUDvRkBSWUm0L01dVc9uaZAxYFFrjBt/pSbhpali8/cGOg56G1LDk1SUNCLGeoc8c2eWPeFYQuG+PZQ3Ioy/cJ6StRSl7iDMrBnJdjJxF9/0xGT9aKP/2t2B4mCirFomxo9Kkq/2Q5zyw+VmKNhraVEWnNirbD7WK0s1qNRT9rNWbcer0C62/lGeOCNRrN2hylZ02cSUaYF7vCE/lp0n6XafO+yG1kro70j/VAFwmzIdKvr1iymAUMQI3AH+yVXz7eneo7bNmqceXtLPURRFhFE/XVJkGbX6yGJzRBD1Y8/9jOx7jyMhQLC0zp57/9KLdfrfy0CDl/R7EssLK6TRcxFGwUNCxQ9CAnLjO4nmu2QuG+SnMb3yIPUu2CVvSibaYVuUU9XzW64vQ01kpK6F6178oolP7LclIvG3vnKYgLIQsIEUdDUGEfahZFhn46oOFYjq5Fnet44lp6ezO7o1o8L79zpvZhv0wRvWSRUtTjvIye8fVkzYLfqwx1UGWDZj1wApeQJAtk7xUjNmfFyvLa6UVra8c4lDa7+9cVYAriG1693aF18OvccAtCGoPqudZ+Z61J6cLvWrLv29ic3utA5K17BoT+GnDHFTslc
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: neutron-rabbitmq-password
      namespace: openstack
    type: Opaque
