---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: neutron-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgB0RoZOKRGQT60CZ3yZ/XwRpel/0SJxBztV0k6eDne7Q3N5bNWjP1ctK6jryaM2B4KwYb8kHmik704npxU1MgdxCQAq6EW3isns+8OftqvyXSiQ6CKQ3kyAcurWv86vO2jN/qRqyJRJYfKLJyJdIfJ/ngjoAp3dbuRYWi+gZiV2j2q1DqbBBO6h4urroE2TJKsQ/pHxXukcoSg7RhCPpu1xD67yMaP7vwNJZqkLDuvc3GSufYlQZP84XpMNfzqtsG0xa4FAgJWkQ38LzQ0N6tZq0Xug3G3/Vd3ZGqvvwKay0+RckWMlIsIxYVKMA9ygW/sUDFHK8vnfHN8n610ZZa1WL05qmRMuyMxOiYerGnQeC078Om4TLT3mfle6OL7tA1qJwnilfez4g6vKn2UDTwJ+4xpuHxiMxU/w3ttek7FpJuOOE6SpNHrXTYqSld5SRz5SNY5MWL2aXpnv3Wro8GyniC9YGx1aUGRreThWBOsqSJ3YyZOXsMRkZeQ2PNSlyCt1PCER46HVdjCX02UM6hb4ohQdmkNVaGjkDYDf88ay9d+5b7Ljk29cvZ5DU4y6SoTIYAVetG+/DXPsjgsig9OByT6L58IlEjP/a06rIqz6d9Ei1nIg/z/mj32GjWm5fXabRDIxRxXjyysLhPKSos4CPYN1WAx2uXwlHAgwXHJ4As0dEN0wSiytff/4a+xM8tlM5HfU8LuGk2lB1Es8TgvtoV27NV2WetaC0vqV71yQPQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: neutron-admin
      namespace: openstack
    type: Opaque
