---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: neutron-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgAwAUat+Dx7BurSQWZoXow5juQXaMn8uGF5XSC2q6AA+R4ciEAqdNa9cHCwnJqcUw/9Xv094p6UAikLmMx8NOzx91jSIRVPzbr1M1F7u4Vxj2ectwaL+A6z/UxCQUnyPowX+GKvejKr+EdgMqkMC5M4ZzJGV/B27Ru52Gcpp90M2bUEvG8YYJsZQvthATVVT87nzC3ht6N7Eo5uWcazsghV5pCFQNpFzVhkcw15mPTyz04gMUFdLVQaoZ8KaTFbJ3ZywWQGdYu27AOweYlihbyA0ohD+WlBe90uTEJufQgJAvYY+unyFmHcUV3OWmSBelL0EOXEZVl7dzxbVmc9Rsts71RmsPqWMhcE2CDurfiUMKKND3Zrk1+g1nodqt8LBYieTYB2900dBCu7ohEhRuniVavDkCBdFnbf4pobhO3QU+tUmCkOPuy0f1YoTPjFv4bO5mwOHWBJjJfBWFarOl3f2jj/elPhxR/TSFm8a4ZrIVRKtI5xTK/bJiJFnruJenNkvZga4bPmxW0IoYhtoFMK385rgrToLiYLV0cNCqvs9+d+aclP7BLx7ya67xVrqm7h0PDJbDkHQ29tH6LcDUaxjyReSSolE5Fk8b4SosAxfUUnB8lsRwGUL7FDrJu+7dmlAgFMFvtdlqkgBgXD9Y+edQXd/45b/gBDCFed9f1hGUvW8etwxRLNKPIYk2W3LQHRBhvYaxa4FYmKuJZv04xHpr4EiuOqXApnIqsxvcyM6g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: neutron-db-password
      namespace: openstack
    type: Opaque
