---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ironic-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgCucgdsmFj2CAj1xnWUOMJzD9Rq8BJ7ZI2usq9JdP75DNYxgwACFO4lwZiSgwhP85M0oHLZm/fiRsL+3yH9C4wrIG+paTAskF/FWBuMHyqqOjEb8289q3qf2h7gBM2VMcFKMM4vy7RNpZizi6dhptkv5zwFshYpg8+HzSxB8A4HRYHnlF55YjaYH7HpB6WAERCscPPcDHDswaK/mSxeoc18Tv7uKlMq1mLtImHXXZSHwvu9De2XuDYn5yN6yYV7tl+f7/cev1ZxUAZ1KYDOqcPYafvZkV65nwjz8PEUXipaf+y5kC4M1pebcYonxJ0ow9HjdLTwBHT3c5KjwPAp9dx1iSA8ruvlr9uIpLjHrmq3oKunQocmWf/FBcuAYOy9Cd17wMjpXHXEb75YKF23bhguNfYKcQQbodKK82cCKM3ggMj2ThK/XWRDRLWg/8eBMd0NjOLlYNJGP7vYgCzM1noGAwtuhHMadHWO8Ak5NbSPjPaasTelElFu/pzkmKB/rHtegvOc8mRz4DadROMTeXv8lehRKQR3dEDKWm+uKyS463itmoV4ESmHBCSylAuke4q6h+HhCsl4ahaXNjzBb2fCWuFi0nU2uC/SibL7odsjzae+buOraMszU4vHZ0uX5d1aQmNLb33HQ83haCGSr5RvnzLkrKMZ3d56eMr6vyyJVJ4a2sdYqV9TwYb6OwztmP+Jjte5b9QHUVo9wYIjn5++T9sCd6SGr3y3hUcPi7NR9w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ironic-admin
      namespace: openstack
    type: Opaque
