---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: placement-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgB4mxMwqtj+DLhKyAypIuq6BsQtJjYaDWdfkIJ8N2d3tpzKoVjwAE+uYBJ1LvPD6vESuUpBrPG7bhFkYX8rEFtorK/4BZM11oyWyB4wstX+4c0ubM4SxtkmX+sLmk0uwcPwvnSax1GduY91EkXDJYFvMUFTrrChw74w6vnCqL9rLNUjb3BQNrbAKylC74N/9Rwx9V/rey/NyVP7+MKOyuYsKlIueTUedy/U3zwcPiODLgXvaRpj3opQTbeG6e7ZF0hv17D0V/SZVI5ftLLQCVw2fkUNArSUrdUUPJyUh65g6CYZHTgd6vApyMP6zd+jkYsDPAfUSPkxJbzU9njuQ+0yg+JT8LzUFeZlDukSX+1tKjBrfJTkU2EMwVtpM7XXxIbzXZQBXdCWZJrps7KNRHqgeS+rF/jBRMoWI3oYqKrNht71LSeRncD5omLdsVJXojCpmJNKNGUcy+P3Y+LkbhswHRBHYv/06BnmItzAI54O4lwXBmb0GaS69vx0i3ucnE8f3GtdRY2TmdyWx6KwC4m5vc7bVQIR5Xo183Q394N54SKex5poh5ZclgmS3Fq+wMDuV7y91XcFHuRIKyMSh3N6tSuWo6oQeFIdW0p7kYVg+gB5LbHGdaM7LTEcFLpYb/klSeUGgiLg7gVbJ8cZLEyRoBSVShvWyUomhj0UTXTbcqVpdXBG4okY6wb6Oh3uJIe9zxPSh74Inpb+P8ZWG+BozJTUNVe+GTcobHennBIjWQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: placement-admin
      namespace: openstack
    type: Opaque
