---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: placement-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgB3jldh46SCwhf6zp1KAX4QSN+E1nHOxS/jx2E0nF0oNqtUtgdS8EvjK54ixpshSqDxeHTCOfVaehJT3Teta0Qm9gx8/NKYIxahzIjNVLYPmNP0McnOUL0W/1Hdbgv0/pnG16L2kNmSFT5jSwzLpEsiwbodQgDNUdgXPB7bEIh3VOIqQ30iDgoHM9ImILV+0NGAKZ/fFeZa29lvAUDQxkL9sR230LGgioa5TxWYjz+2hLJg+M9N6PFdx8yHRz6Ia5CE49hRtMfHUBY/QFuDgMxa1XZgfRDPeWZVNJjLDFE5B4zuo61EuCpG1eqnjP2HXnplbjUNcbjuJhDVjuDiE23HxI74RE7eU63b2/ekkU4/5/LaKKljle60Ok5PS4nAFXqrGSOt8bPrh/JkFexF3XCVu4KvUK2kAq73I023v5m02QCs/TVcTUrw9qRWAIUv9pIKCIix2jHkiky1kPYZwmblzkdxaew21gFhiLvyoVoQRSbnuuZbCPn/g38KPr3kAtYkjwhag31HE9Ak9q32u1Srpq8pweiYVvltGzv00XMP+zxecbL5KKy3hOyH3y7iih8MRu9f+XHHNTBzM9sRPpukS0uvMdUzR/b4ZQ/4ae05KEQYkxMs9H1Xu+wJpHcf3wC7JZFBPSqXnQLn/Qz3KWXNuTvkRKf1NlZfrBs8qTW4fkBruxECSnB4OF0cG0UcFhZKrJRFHpBEQp8PdEQM0KVKriGMu3SPw1g2SfswRrpHvQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: placement-db-password
      namespace: openstack
    type: Opaque
