apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openstack
helmGlobals:
  chartHome: ../charts/
helmCharts:
- name: rabbitmq-cluster-operator
  includeCRDs: true
  namespace: openstack
  valuesFile: values.yaml
  releaseName: rabbitmq-operator
  version: 3.10.7
  repo: https://charts.bitnami.com/bitnami
