---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-rabbitmq-admin
spec:
  encryptedData:
    RABBITMQ_CONNECTION: AgAy2bILtR4J0mrf+cjPdYXfJa6nlXydiskKpGNYiqNAikPJn3itC2ZM4v8R5bf50dNakHANCNt6heOAB4LrF9zb2+6bnaekVlUhuKtJQHki4k48tLxKdmLWoURUp2Izlg5lNt71btoEBNVzEia+oAVwirl8k6ZLy80F32MXXTRPtj+yzvokOYvfJqGZveRejVdoXJShT2Pohd41zfsgu5NQWic/aoahSlLukJU+D2c9Rm8tC5oDGOW2evOALz8cnLwFymiZM8+FtN8dwfsS5llOqo1KhvIRQE7oVaaji3WE/GuCknTAp7cGI910VushUwX21cDnr2hmkmr474/Qc8cgrRPN/kIb5FvOWrPF0JrU96v2SFr2HVOjJnglWwIumiBJ2/AfZa+NBXuo72doEaKsyGxa8kibyUK7OBvCMy7ZgA3qT+xQWL0ki7T6WnRRYgZ7Kp4dbgJXtBCCihPNfp1sdMVqScLTo2aV+xHDywonapR0r5jIT8AatGK8qiVyFUZz0WMFF4Ufo/VZV5SP5LBNW4dq4bv7u7/W+F37D5l9DaGsjABzOmLTZCw7S+mAilQRNYrgcJQ4oW+yGR3/5tB1lC5aDd3Piuf6MtIgpIOGLkCg9HBn8KZkn1++hIss7YsZPqnYh59x3vdFL/Stj5XPO1PWSv7j/a7xDOxBnozI6TIhcJFFwNjJvXm1SMmu0+lCf8agiCDk4wMTjuTWDR8fpZ/QBiTcZ7gHCyrtoGBWsGUlPOr322LAF6dA2iHcI+6pvqLDuk0ZP6a+s/GefqciM2loxAnTg56Wq520Qj9hQ8lAMHJHsnS3U10VYZSg2ihgmVVTT0+LSA5bmRE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-rabbitmq-admin
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-rabbitmq-user
spec:
  encryptedData:
    RABBITMQ_CONNECTION: AgAVDqeUNHS/Vc4K5gy1LkHpBh9+zpg2RYcwa7HpJu0Ze4Xg5u4OW0+JyRhwHpw3k56nos/00T1pCasjFFKG2cAx9br4NT0TeDLKX15o4OI7Dj62PYEH4WwozA3+aAv7J3jcVwMPHBh4Klxm17Si+DY7LGEi1MfWAAs2X8XQUPt/ADNfpFzXiyQCP8EoUueLmNKQagsHLU9iUAthNh7innM09MM+yODpnJsU0lP9mzzNaqpnErw/tuW3DyKKD1Ie8/4hAxkplM4xbV8J/b4Rhwy9pkCyEeojwpEboKzuUOvYVAc1rRHeJvny7ILO6lS6jlAq92fG+NfTRVWKFUQR6AUF57JEFUyf6KtY1pW0dynNZ1H9BhwaXWaBU6FnxX+yoYn2lpQz9AXrwO5O7eB0NQ4LQTTiTWIlQi0YHWFTry0yLQjUbnecXeC3s+Qc/emTA4FGvb1M3XtHknt9gRDbBNeeTY1SqrXyLRenXgjLITdFs/DwQQSV1hZy62wHPSNJimwjxO83NayR1iff2I97htxVHZbVCTPL0j2aQ6ngK0Xi2g4OgntHztM4Yk4fluAIrqXM6yNd83QQv3nTTOy5kOTnTPN/8Xq8CaBItevhMb4N6Wf1hsewHLRqkmPWMZ34vkJ88GD0wDoyRd251/vOadBuj3lH8wSkLOJPbiDZLLgTt6Z0DkYytsKd52cs4nCHM6w7Q35rwd2oeIATM8hADhnaYEWs+XL0SgK1jaN+aBB4k5LDOXqmTkeBB5ebW5KGXN1XNumlBtPVzSnQuRNX6uYW1SlIv8rJbLv91QTeyU1gwlfir3DHmo79RXRIVj94mgFERF7FMdwrn55no44+yKRlsa7EjuHkbFO/jrnCbEhQz1A7AcI3tspbn2WDUw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-rabbitmq-user
    type: Opaque
