---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: octavia-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgCAoQBuGdZY4+nZmmIkfoo3zPtFYVk8gH2nYLnH1Og7E4N4zM9vIrpA4K5tJ6NoZEWhe3yZpVnbUKEkVnNgn0GIm9q6QXD035a8T96UCB7DA8jxhXM42HEeLq0bHyouKrMFK8ZsZ7WGBOMXY0lOBTZvdiSzvsRaE/aSoTnp32HA8/YNN8of+KbAtR+wLu5HfAOTxw6LiLu8VCzcGz/yf048l9v59sPk9nV1sERlmifb0Cc7pYdRFHFP1FZSJcYi7uKmLmWGOp5GptxgoJFwvAeqFlQwfcAg6phesOZ3ccPg1w5WAMQ1UH80uZpRmiZS5NTtP34NuP7mT6tS+3yl6ogZdqsOEvmZ0PDmJUgLlLUACJwSzpMzBErLHNSKd+TsxlAcLJkf03ldroqiW+xDALks04PkyyU5yYZXwCdsJGjsiSUorKHVIyJ75fEXUZ0eHDxgEitgLBGoIc2cWZfTrrthS/9MuFx7A5EvP7eMJNDefbrmuCitkDds8Zmc8eFG85VM7tA5xibj5dU4/sdNvXyiPCaFwbF2kG2LwgtLGeXZH1EOgVuzToFx49fkhuSo4qMSG2U49WFS+5fXTVK0Jww2ioNg+E3wdQ4o6aQ+iSfg4DWQoLc2GTktOwfe3L45YybPhxuIHD1BiYJmyr1It4UidN6lfJAHHupP7DwjM/RWqyYTR6Ele3EbDP6ojU6FWuvAHEDP+f+YQ10VYpYL8xnqBSLPJEbZS4rcWCPf9klNgw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: octavia-db-password
      namespace: openstack
    type: Opaque
