---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: octavia-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgAiWeMGbb1ar1NsXsUgFJOVCRzhASxEezxc8e1H+WE+AFbqDXNltT7Em7TY3IOMgk1moy+jLs/Tf/QKeXq8YL3ram8eZDEjVTYQctWXudIHIXqMHSv1A5Xap1+Sx3w6iD25vJ4IveWwL7okRw3u4Y2rRnJ75zD+47UiHTDNNMKyXsMg7Wh9wQKJ8NAZRFvEQn3Iqchv1scGJufpBtwfeC5PQiIGHAQxKoPhvDKyL6voR+JuK1DOhhF6Ii99BpqjQlieN9EW2JgJvXwKKtmZlPmFeFEj7Q/kb2odPhRwESZSSlIfNvlzJmoO6e+KECqfQj5jkRseX9PKDPRcUt8sUAecfbld0Rla/0LzCpWTGsgys8T7gHj4hNsXYMvBJQzoDKS6fkOVx2EJyLMLDlRm07XmE8QxadFRPhhwiEWCRD2InLpeB7EtUZuyVQz8Vuupy+YGvjNKC40TcSVN1INREMelj1GPs2yGgscLg1gUT7nKs9Rlx5H5VVXL7nCoiU7HTorOAmXFoQut7yihv+hKFCZCZaqYB3RWRzSt9GrNwMP3VNxAGmidN6CbOF9nSQ/LdL0RS8ly9ij1A1dIihzdbW4BJfxS3jIwRqq/eh1VF1l2XwAIfhVsb+sTek+WjoADEUkFHdGAQIkQ4eMNRmugxQML17rontSOXfndJq8Ctn6FsadYPbWDb0xDtOqIhquiOWCZmjhEQqqSDh6OGMDa6uzOa6PlrMsP+3AD+shyeAYYa7YvkUinJJvaX7Y5YsIdTAAoqAXFTxqZWkmihlQSnwCA
    username: AgCJ4uFm53ugC1pR95j6M2aw6b4hc3mxNnZuJuWajE854CFbcTEOut/LjXATIbPTIBp6xWz81EsQ4/T3CA4WHytTQxBSsPbq0npDdz4EtdQlFXna4Orrlp8TRWkbZ/aJSsoIfeR9/5RybO+nuh+KVOOA9YIzaapTfmlbrLtj/SD5V6kZJxvHOvT7U3Xujv1PEy80fMIgqsmtxu3dyLkve0UG6OYqj4+lXAJFzQtRteZ5+93WuFr3SwheAkQXexf5TPS2YsBUwhKwKNMiXIXhieQp/1XCBVZKMbDBDg6F+TuOOfC2JI7rFgzckE9dcx8bnTMYJ01GbuDkBOvLKIaCEv85ezkjLq84uJbp8W1R1+2sD0tmhd2zJuovGnKjatr5ZM0NZLHZzBM2Fj1ohGJezuAdSP7gFmgzAR/X7NZOfYW6OtRKiF+O2OUrWOUQhy8tGRjjEHj4zbfduSmnqW3kv6PKFUtj79zgLsZJyHcpaQyZWYVmmvlATXDlghQJN64FS+4dC9Y+z6LEiloqFWgvSEQIrOyR021TA5wqfXU3CJQpoNZ6xU64W+fHhxXhTHknZeHS4cX0GEY1K+5oT7FMOxfd2PtrVBkIG2nqGJsRkTrGE1Hrng7gXrhAUPYM/l2xAoO5YokNxhQ3wnUkvTX7akqcZDUpKS8DpSRKv6S3ZYaYvwXv6KPXBrA1cfdk15TwGvdB5R3QQNWQ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: octavia-rabbitmq-password
      namespace: openstack
    type: Opaque
