---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: octavia-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgCrSAJBZjHMI2feHaOdA3HWlCsfMtJ2CKhjx9NSaC2+aa4+u1JG3oRws13K7awNnOphAdk04IGPRXe8WXS7LpQK+3eQCeNhXGKgRDHCcAKV1xS2QDp9uz5NhRBwPsuvRSPb56rXdbnAWFKB71twaWP7zAWWLJZSEEOzv/hZ7eGULUlSVsIawPbTPBR7OoRl2CZra0bap/zsQbMH3v+OyimkOrS8VO3UXq40IYg7Z4jRq5i+h3yu/Zxfp2xolJk+Hf44mXoI9/QEHTjl4TAs2cCx1qaiLdhB6h5Vo4vAuMytR0FingMcbIAIhhI4mKsZe1ArMq4IF5fyPg0TyjM6MmoisRgMYqxmJDEK72Ek5Tf+llkFmY1p3h0mEiDJT7V6J3VglSgeBQDJwtCm80vlafLv9BZ3sit8pmscXzCRdK22S69pOwM2w4a+jeitYf/Wr0/kZALGoZ/Ni/GfFfQa3M9kWluBpZQk8kDMiW3kBkET6fObVf5iEyb7lEGr8ACpG1i/oGhYZXw/e6RzPteftbrOslfa032Xp6X6fYdrJUr07vKeNu121iIzuAbTuW90672q60B0fl6zjVHrabh+oceJuvYPLSJtQ6LQb+YKWcZk/+0IiMBFK/TuIg+1HR2tFEWgI0qaN5omC3aleGHA5cMMxxnittzLn/+y/TA0r1nJ7YrQF9uRAezKRUPoXGDmfnNX2Iv+lSoQvwfm4P5hHYgoPPNqaba1WsahAv62qHSfGA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: octavia-admin
      namespace: openstack
    type: Opaque
