---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: octavia-certificates
  namespace: openstack
spec:
  encryptedData:
    password: AgBDkuZ4wMOtAMbXvHWe5G1xTCyteWYh3p24qj0nIlFcRuU5vv9MHLMK39+p4URNW1tmVf20EH5ZRxNNfu2mrCpXBE+My66nPikJny4z2oLBYPS1ovoD2r91c2ncEhDpVpUMPNh7kNmnfu29mHNF1bnajC5XGS2y+QUUVkxUTYWk8+aTiik7TSbKOcN4GY15sJgoylURatXSDnAEOiF6Bo1UdgbwwD3HWAvXpHbFqYlVfwaenUQRJRwZSvhekm7PMHQUtmj6C6azUcM2WQvkaptONW74SDG9wJ5aU3BGya98/F4eaQ1VwnCpR0wK/LY5muRZOXZHc6Z0pjpznMGvevoPNxckMoPCCqLqNqD2LEW6gdnC+THCXnFrx+pai/HPzKlvf6SPsKE80Tc72oCq6R99d1uCu0eKUkJ6oClZafGyFYCvHapShOnqlMO08ebV+N9K3PM7t7rW+RLaE3Tdnk3dd596kNPv2wfjVfNZQV3LrnXhGgqAQ3RUk9aW43LGBG+qXZaoCO7LIVooUGw+v8xo5L46pXwTpfyARlzg1bLTfbWsjiDyUFV14AMSOruQNhj0NtJGoBC5KL/A52NTkRi7kzU90RwmJmEEyp41i8DRZXJtepOcmLnsC420p7fUvNZSznqZIfw0qX2kqW3cOXVtzxe9+1FyZf2zCBQP+siEBxgfnlWxsAwMs8n7OSzlPN7oxr7GvOqTtTl8jqHXoP+COUouJln4SD7WM/NuVy7rPQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: octavia-certificates
      namespace: openstack
    type: Opaque
