---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: heat-trustee
  namespace: openstack
spec:
  encryptedData:
    password: AgCaIYZGRJeH1sgEOYo5K+3KHpYEcM0sH1ckoRYP/XcAuRhpagmORjs7HF7ZemZsnRITu9JRay+VljMdQWLifCvxiPyNuqjodgi7TYp/JF1NWyv4xbraARWyhxf+EgOsp0iZ9tk67BPBAGrHxGreCIiiqGLETVtR2GXrUVi513zUkPP39bdmGCPyCavJ09ZaqJkHuvg7//h7t8tixihdJOHc8ch3j1iRy8qmOCfFpbu/h79EO7AENOiaI8N0/YAbQtzrMrli+IIXQqEPfUEiBGMOawbVSF/7yB005mTRnp60ymxtd0OIYz1XXEJWyVEzysrVZrhCT0R5VNvJrPWuC3K6vIHHZv8ROFef4cV2Rfx4iYIJgKeJC+iuzCp5VeFfxfADIZsqvYxWbohZUHC5Q2vlxrUEYtKPEDT7yfD559INWRuMjjYM66u7eCezv7Nr5X3USR8mQdl7Xc19jlAJ6uN7EwsyIrdc1gMUmhPcEmwWPeHWjjVXr7RuD5lvh00Vv9foEkcxisw5d7/oU2EFC/iU0/Hqqi1sFp2eG5BSz+A+vhWmdnXbC7Jx2w/ozncNTWM9RGSnhybL9a4nY64a8P2OHKqCZaxMT6p337THh9oTVtb5C4gUBnPJGXW9RifgQK+MpREWJW0W8+HIIxzJ4S1VKxLwGid7l7PsvKSEgr79dT+MtVwKtplVxnH2aN96LbgxOIMuyemY3z43jeY72U6Rz3Nwt8Xl11FCpY99TyBPPQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: heat-trustee
      namespace: openstack
    type: Opaque
