---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: heat-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgBqL2w375aC79EQGTme1tiW1lfeg6lUDkdw2QTNhAxsCVl/Cvy667HshY25hnNgT7uuOrGcAKGOWCwJzoEKwfBW0t+lLVGjnwhBEdu0JtbtbEPx1cnVya3eUFMsb+m0d2J1b5fKy1taQmNuFCpcCwyDpJ4FjslRgERjW5k8JDU9oo8moq/E6QpNf/73133YthriyV3H7orVx0ow1hgQ7Ms6xQPlIOWtW9CpOMomXn2KT28kTlDqaVCJA/XWdsQvPd8Y/l4R99F4s7IbjFIf8TH8fTyDeLuY2FzNZp+YUxS/W4pOkXsC4T5mouSF0YlewGISROGqW+AxM4OJy3Jo5lJrpgy3e2ujxZKAzD6eyRDrza/Vc8Qjtdg2HrzXayAfJ6y6hFloMt/VWGFru6Nte6rtjuL3rVbDfBlpk//gHEXFlc4k3RyeqgFfzj9t5hwzqY3kcgqjwzbptIHLIfunoU8sz5t44X+yVHVSxPi6Ga6q4gKI5TrYSwUjUlGDBAjzQg6r5WwMbGEDnoliXMKPQdEwXpJo+wUBMnS+kQk1f6qHHUPqBwyHAopf9beNGkG/xSPVc5hbsSyQ3vm5VhlVgyBzqiB8TQWVu+gdSOC0DdpQimQN0uXk89CWDECh1MwMc2ZI7WAmuhI6W/IMrrp67LbA3dTRvOMHNSuBdwKdkzRuhfg9IQOhg81up3Jj3iMpbbBk+yduqHyCO3FtSouCoIr9n0j+4byfb3f+fruMOTPhGw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: heat-admin
      namespace: openstack
    type: Opaque
