---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: heat-stack-user
  namespace: openstack
spec:
  encryptedData:
    password: AgB2f3KrgY44Wq8NBbbS7JoY25YsNv/dvPq2UOuNwksoutL3vCt7aH1Tilrzfnv0ilHZOZFVkdTZEQqJg/qdXpWGyEUCakBNvA8/AFYn7JEURcTcieEFAxQf0semHWJYs3QDGSJz05DKCQMw2A8GOi65+FSa3WN6KuwDOfVk9wfOMhFYPz8RHeOv5n24wer8dIHFvtiEltDmOMc/3LYfxlfKtqJhXRbCF5jvwjLjIoeFJv6mfWjp+2Z/DeOfMD4Lwp7N7Fh4/ZdBHuSp3iWOtns3fOM8fqCXzF5c1wpzttGGyXUfzBxsSrLTAUXVWoPzze6Ix5HbK/W4EOXhxQ9myqCb8opjE5leAfV0Dv6tRXKBcI7I3YYzHw/SIIKyybKpgs6+/gVkIPXKIofHVtVYjt06pIb3FbXaoA6LRKKH/S6ccnMv0C9XwFAvpwCXlEHRWcy0WR2CHJoBWBn+BJtTOgo8jXg39AIVcLtFM2B4ZIa6e3Z2/qxVkQwbGgEg0Hv2xH6/pJI8tzdIpCIzIQQujj50AQgIUcEZlHN6AeBvDWbnrJKkktT8cU3XokGo2ScRL1G6HVfJaPU5OK1Y2ys3pzzC9KuXqFddJAQVMTy1edHOF87ug5jq8f+kW6dEn62T1OjmytYCm4oESOKGSlucn+Wn9FgCzARWCFkrRIR4xTdwSj00z3xRZ4yWB1U2Dmg2sAXfMcOORg/lPTFF0nV5elCFXZVHKELTpuFY8aIoqcLLzg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: heat-stack-user
      namespace: openstack
    type: Opaque
