---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: glance-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgB4RfUcg4EENHUdyFElcComviKIsHWhoJeTYC6o09aBQb0P945/JanzgRsXnDlWSd9jfhK6pd5XA6h6Q75bfbJks7zFXwbPHy1MfOMF9ta0ZEWjD586bzUGXlyeCJzgMxKsXDq2nmCu/YFIFyErPkgkm59dqo35daIvShbxB4VT+Ab47cCuBiSi72IyQVmFaU6XYNQHH7Qnh6U73nnpYhyF3RzCsRGf1mgbDqN9mquGqYwRwX+aonjZbNDkluN7Ej1a5wYWL3bWMJeG2zsvDno3Qg74P2ULmlHhi+Ll6+gYo8lyVUS4vg6Ob9QYz7tZZj1tAT0TwMk4ce6ihC2AEolE3zOV3fwnIX43zM747sr3rMrNTj+fNUl+Zzj7xGp8PaozbzR3VqN+aVXli13ntHNISKrTZbI1BMK/TUVqyzQnv77tjYGJfhCBN0OOKiCm+aH9mRZA18/SXJd4x/J18b2fqgYhoTMMLHSSoEiM2SYT7rbeecZ7R8Fl/qzLBs01f8rg9wnv5Grcv9plJHo4tPiJ0Zk9d2qdVclSotKezuJXbv1A7Gbd765T1QYBSEznzYujLg+aiOhJI2GiglmNTBRy6XmwV/dpJjFr4zcSVFW0shv4+Jw0hjIr+j8KklO2A92gRG31uSUdvOvQt2yfPrBZLN6q+jA9CpNzqQoK53kZ/GeNJBhhI5Jy7nQgLrgsTdGILKDE7hk1CjhiddXLibY36Hl8DKvfN2e5Nw94fOobyfbqo5np8LPxkXPibOWjmJgwiWUrioHv+pO1tUNTo4f+
    username: AgCf4JUvn65IARGqVAKGgKqtCzCY1IM15OHjjbb5bcNjoLQRKpE4DWM81kw953IvzwtPBPFdUqRK1zmUhnwz1Whfj36hNR0/2w4XkG7azFtFL9XRHM7+AqcMzEMzN28q+98jL8fetKwjINEFYscGFX6E/7eKY8NTRUOXFLJ1EJACvNF3BzE/9uSm2SewN182uSm6lNu1a5JJOI1eRTvXYlAnxHDBjdT/LiE/ASZkq3WSVEppwfX6PGtIvqTtVtnn05epYRQ6JEXRAANwXpvi1tbOgFm7bTjJcLNG2ozipmUT/WE3xJsP3mIyIkgHKnYoHF6OMyXnSZDJyY0HV9RnoiJe+cL98TANcFehTZVBirHDwh1EDGJbJ9fMLibvAYU+pbpNlQEvQOw7AvzDpIHZ+MqWsKu3V1rOisfykbOA3EtG3VgE+9mct+yJl2m+5b8XRil+GHdUEHfki6Tq2EV79zBNq89p5V8XW/Y+vPzHfr/Jk1HW5OO2B3+eJ1gr3S03qvZkZGSF7+4aKrXZHHu6s4f5XMyR+98sfXdrcWhnX2n76CwnQ7ugLez32VXcMQ3HYpauwEj67aim8wtiPKF6YNCvrTsaNDaZYQEWqm6AlXUytnvn9zsnHz5rVbP4tckRz2l6wa/1PioUS4GmpE6o+cHe6O8ZaCzAD0fOE6rYVkCFtj78Hqg5LreWtmJJsVMIG9VAVApeGNs=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: glance-rabbitmq-password
      namespace: openstack
    type: Opaque
