---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: glance-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgAVAmdUtCI5xSx4vu3AFHA52ffvt7ucur5XR7kQQsI9YjpzhY5ySlCJLApTiZh7pMZp6ai8Tu+dv9Qb3iUcTJvADyr2Z7l8QlxHTuwDdsbOi8ygIymh+iv9HdFvfDNDzN6p/HuBcWFiZh7X3+7UpuEeOEGyw0Vwfab3nkIeOeu5EZvOozUj7WsbSCQPMe1SeRcoFh4COilA+ixRL8rmeWE92F0mHYa9vdNgJy1Nh0OsZRqNZGGMccqFs0XuBFdv4lTjMHtnAayNqH450uWo0aDhKDH8pjZGtea3048+sH0qF4Ecz8gObTRtADeSaEwtQl9OFgpq9gKS7Tqb3jQI8IalMdnuAQfqp8qDOx9I6cJcyOR9d/Tx5pJg/T8t3BGK6jBND7CjzDG4oSbnuyARX8oAT9jnZHaW4I6pTnANmVOpkKPfuWNc3mfjeKfj8Gmf1MpWCy7EXdtFxX4t01fFxQsC+TH/B3hyljuG8auoTovr5sSsR6F0WePM3CNZzcedNIQvWXpbeUNfC4UsGprKvGK6nweD1IoEawRUsESj9Yi8d9rTD5NoUJneVwhMcThMpLfuAeC3to7XJyxCmiaaFS7zgY8SVnsELLM6g4FCshsL3UtR7kKNhUhIx6/0oF7yZPVSqZgM8txOqGhSe4SiK4ldSzlGnji12LMjNWnNKgXOJEXN3+Z3KybKR5MZ1Ca9CvfqfqdNekZMv3JzCjcnMvSYoI2bDbEe/baSkjcDPQyBqQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: glance-db-password
      namespace: openstack
    type: Opaque
