---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: glance-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgCkEdWNftKArhiAAjkpcQ9Q2f1Oejn9aIaVqd/yzwuAwGPHO8k6qNMfyNdWYb3pk1B+AcVTDfg4SsJ9/vEdwHHRyc6ofU8FhOj0euv1Rtcd44TGTCKnhgbNzavNCGRIAeB4Jglh5DpwQ6YwzPMARiUr7+1gpp0RnyPPJWfPDPQVdJ1u86gUDs+ZXan7Y1T1uldYrhjcSbWq/VD2S9rEM9bEUB3wTHGUpocv8i9oOIlSb2pZ5fpvh57codP7hc3lTIRghiJpY26yWHlID2IYUoTzKtiZC5gVlwbMkucuoZGNphion+FsvEGhRrQRhVKF2NRIfCbBLQ1OgwwWMwKxkyTTZdZP8pJLYJIL4zeHYUKGscISl0s0JcKuaDPeLHKYWnTPIwVPsK5qKgn81Ha0ZFuIr2rhteY6eIhKSsKSsb5UhecQ9rV2aE/OmN6sf9EYdqKrNiJrFMOWdjBU19dekdPq6KxYdWKOaQX44P1mlYODUDqxYDCchFfBr3hMNSA/x5sD6rctofWMMIB94vOTVYGTVaY5PEHpZZBJ2BQHF4NN/P3hhHJ2ir4UXu8fJLpHRZsu4eOGHKDIcHxh2aiN8LqNd57nnYE0CxMEv8i/52wGTJNOHQl/7Gz5J3rSU2fjonOvXtdJhrBeK3SZCsHUbtys5Z4mPO+SJ/d9Ik5oC1IKsnzF9l7Sq0lN1d2h4IcPfnKZTj69jApZbIhLK+nOjayV0iUH5hFsxnH512wmlrWTnQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: glance-admin
      namespace: openstack
    type: Opaque
