apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: horizon
  namespace: rackspace-system
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: osh/openstack/15-horizon
    repoURL: 'https://github.com/pratik705/trinity.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      selfHeal: true
      prune: false
  sources: []
  project: default
