---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: horizon-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgAVLVhlszaVjdeZTGSaLkxg8yeGTtOVc0TuvyTTg7u9XR9OpnRJlVqW8QAJPury727HgkDhCwSCx1J912OB5Av7AMb5EDxozdNiPfibgHJxGJHc7aQikhX3QiMzCrLVWh03Ts9zutMnp5msVKelFQjQFBNqdo3Al+wTt5gmRmBS+5/dAmT9oO+oCjyx47Pm8g3Gd5/udH8jlNFK6B/zocTTfrosbJ0IXfl3eVHLs0qqb0V7kmG/JC4725dKOU/DoN5AWWPACdGdU1BdpsTvlhn6B8jM1noBgIcC9T8Uu2Tj76mAga3C0FURoCCq+gXKrdECIE9pSx7iIjMhKsJqo2Yl/nlEpCYbyono6Aml5o6wOLH6JDzvNVp80OHJLoCXM4XcJnZXeqLtIOnZ9IlwfDRWgaXAvvtUufSz1+zrCqRVT57K6nh4yMWSNe2zhqp2o9Umi6Kfha1cfOf4Bmwllm//Y4yKMKKcGZnzX4aqMh8RVMxjvoR6O2wDc5ySkGKvTKwHVWvDwQGXyRrwNjxEuF5BEFmIvmIvWf0fS644FIkgG/ipe+Avp/GHxBwcsNsotBMDc1ZrSegrlunrappNhpvX+keDTI5OpSy9FpRAGdAUr3GtU/O3pv55kgXKhLvJorvvtEjXrUbA8AjhMRLOjGeJnr8i+PHAKabXe8gDpJ5UWGjUhQp7EAl1x0Y1YVnECET1ShBWoK7Q0pIlfCqxxGAVIB8zJ/onWNMuqJI6eGEucg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: horizon-db-password
      namespace: openstack
    type: Opaque
