redis-ha:
  enabled: false

controller:
  replicas: 1

configs:
  cm:
    kustomize.buildOptions: --enable-helm

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      cert-manager.io/issuer: rackspace-ca-issuer
      cert-manager.io/duration: 43800h
      cert-manager.io/renew-before: 360h
    enabled: true
    ingressClassName: "rackspace-nginx"
    hosts: ["argocd.pbandark.com"]
    tls:
      - hosts:
          - argocd.pbandark.com
        secretName: rackspace-argocd
    https: true
 
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2
