---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mariadb
  namespace: openstack
spec:
  encryptedData:
    password: AgAMz9mb9xpR6SrqAqwReSiZ8qYK/+/4dIfdHRWyp8aceqOVMQJMleeZ1/s16rdk0aQNSPM1O8Vm57wGb4CoYGkmHs5bI6fndR9MXZ11X94TY6mp31c2PWpTkXctnrUKT6mrd4/hzgH9GbLFa/jcMlw9twlZUCJ6n01cLz7V3G5FQLiKQm9OdG7+/5zQLmqQrjzeA78Mqx9qaUDlVpTMDmvMFYsg6pMxvT09tQKsgrXsrtNZ2ZFBklGJ/kMRLC79fAnHUOJujr7q1D+zPbcAbjU6cBPLccYF77S5Jf+syutHtoStPZl6GqC+fVE1Qu+XR+ljGmQfSAWa2XHchAeRzGmIUgUTRYary2gTdOfNlZxWjpYUdItVrbzR46FEQmuF/V4yqG0lYeA36zMspL4l3iSFwT7NyPgciLIehOe3K+eco4SdThx/F2nir+bnWt3yg6MRZnK4xX03H4mzt3gNo6MXo/OpeWk90mXeVkeJ1zODQD9zMzwCU5qGfo/YqUPAsU5H9zmt0NHgqgAOTEFC2D/icl4zIE58hn4STmMaoFh8hEjBJUXaEKFoRW6NIIpJPDtyMcnshLuK2YQc2tcX0QUGbwkuvV0a/mu3YZUVupKmWeXhYoPpUV+2IUP5gAsO5eywSLQYyImJ9I/p8mgDl6hbLDk8f/jFwnXcI1/Ulr/Aktjq803d38ZFg0uiTXKeh3YxSkE2eOY9cEtE0KGxrgd93MWY78H7rlP3D+BqRe4Prw==
    root-password: AgCm+9PQIAjE5znWr2EEq5hBskiiS0O3/NPx0m2ywlE0eOXFF3lb5kODCR658cpANET4TvsoZzChMJ/rtikgU1XT2eEpOtr76kkryfRuy9j7HyQhGA5EIxr7OlBd6zTvnwcLR6uQo9uLRkuRQWoTyKZSUE+AcX0j6h8ONz3tJ4Jox6GjuIQlINX40hv42zFXUCDALLgxtKjnYqm/LF/m3zOuDp2FYqx2P8TT92528h3++UT0lSQtjJQmLbzzfctWq2Z3xSXVjKBTMF/vZTJ+gVg8Bouizgz8q+QOeOOjiFFd7teOaz269MkfZXx/u2qZt6w4Eq5aJ4fDyzL6Yopq+iS2bY6gM2guGE9bd8r/vZHAXvvKazjAiakdctuh6h+WtMYg5zvSozVmpqueL4lo6yt/uO2QmSDGdhCrwEOSmvLN8RGbIL4YSOHXT7Xq4EhHTAnCDKYBbJ49ZO+hhQYmcUmUelQsLspZJaBC4d53VZxdzrOJq2BiUjNEtTdulK86eYi4lfRi8rt2HpOin3QI6XK6UVmMyWjtsu0XYveSr1wrehZ1e9yGyBCJysQjHrERkZz8pV/y31sHgQtRBSD7nJH6FrfWBwz51sF0wU0C8+zG9PHcg69EFo0oTwvMk5g7RF28Uahywt5rMhZrWb0Dp1qxAsi6ijLSd0VTehZZ8CUM84aVOE6QqWi+Ub+K0WYgjGxRVXSp7qLPhq9pPYxTjfSTnhKCepdLnV3ryen/wAdp9g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mariadb
      namespace: openstack
    type: Opaque
