apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  database: mariadb
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb
    key: password

  image: mariadb:11.0.3

  port: 3306

  replicas: 3
  podSecurityContext:
    runAsUser: 0
  galera:
    enabled: true
    primary:
      podIndex: 0
      automaticFailover: true
    sst: mariabackup
    replicaThreads: 1
    agent:
      image: ghcr.io/mariadb-operator/agent:v0.0.3
      port: 5555
      kubernetesAuth:
        enabled: true
      gracefulShutdownTimeout: 5s
    recovery:
      enabled: true
      clusterHealthyTimeout: 3m0s
      clusterBootstrapTimeout: 10m0s
      podRecoveryTimeout: 5m0s
      podSyncTimeout: 5m0s
    initContainer:
      image: ghcr.io/mariadb-operator/init:v0.0.6
    volumeClaimTemplate:
      resources:
        requests:
          storage: 500Mi
      accessModes:
        - ReadWriteOnce

  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: br-mgmt-network
  connection:
    secretName: mariadb-galera-conn
    secretTemplate:
      key: dsn

  primaryService:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: br-mgmt-network
  primaryConnection:
    secretName: mariadb-galera-conn-primary
    secretTemplate:
      key: dsn

  secondaryService:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: br-mgmt-network
  secondaryConnection:
    secretName: mariadb-galera-conn-secondary
    secretTemplate:
      key: dsn

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"

  tolerations:
    - key: "mariadb.mmontes.io/ha"
      operator: "Exists"
      effect: "NoSchedule"

  podDisruptionBudget:
    maxUnavailable: 66%

  updateStrategy:
    type: RollingUpdate

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M
    max_connections=10240
    open_files_limit=10240
    max-connect-errors=1000000

  nodeSelector:
    openstack-control-plane: enabled

  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      memory: 16Gi

  volumeClaimTemplate:
    resources:
      requests:
        storage: 50Gi
    accessModes:
      - ReadWriteOnce
