---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: glance-db-admin
spec:
  encryptedData:
    DB_CONNECTION: AgCjro7a8GGaN+QUlgrmxuaa0Mm58WEwMJcfdrwjOmmG8onYykk4GOrCxG2eidn1aT8R/YmnoQFzWqEC3XDfqrcnCTCVADYUxN2f4BrTUJofno1pSI47yRUoo4JHEAAuaFqjkEKvOMSKW9v/ibUQ6lPUrBS3DyDgC0itxyPIzrKiX4RsxCDVwzU/MfXQkI94DmjAU3wiLI6pQSx9TNoBsFY6wz7iW7IRQp3eNTnaK6Y20bApVSVSQsMnkBpNF0tgEFrx0IcgRHGBiaHgY5SGrjF5yPeDTJVPtoJGtjOhWS/zzXA09MHmY9ZHHrZRSS08yhd/mdgKRYQrzkB1tLoNpTldE/lnVOk1r9AMZubKc9ZzYY0kx7A25Hcx4JHlUeYtATT6zHlgg+g7cEhHCFMSmc3u+n7kpFX3KPKE+nu+CWTcRGKZbZoyQXNmF+Ik9JLxNzB97vl0NHkCcnxj8arU1va6Cooznjf71sjHPeTY1skDaEFChpltii592EhSkSoA4Ffa/UaWXULKXENdNR+s+tJq04X/r0+/Hx7LlyXl14gHVYenXqqGAWwld4a6HFBK1K++dlauIJtjMvrZIZeQ492gtGzp4B9kZc1yyP4yVCyRpE2reeoVAlaFwXCCgreZJgkM6nJY1ZSvvHWx+LIpJFohprEMN8PnrrMyPcJRueJkzThTFdJeqVA15ByNcN7ud4dCPS1Q6cmDMxAXbir8ydb6ppIaYiR48cs5W7VK6Mj/61y0vKmwPsqWPXS5fdcsFVGbwya6vuSe/qERL9/3wvUX6RfG4yUSdxgTg+2b9e+CNaga0RmPB7VSWJ47Djv3jKqmXFdOnngjIy1y43O683tQWuAMBQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: glance-db-admin
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: glance-db-user
spec:
  encryptedData:
    DB_CONNECTION: AgB07WlHAmiEPQ86Z3wGA/vHl1SwkyEPIV0G4uJLziO1bH/DSalw4wSIrBIq2NMhaVjJe9bLQ69IVInAgbowVhDibkcdbf5RYarkH8YYFD2dDsH9gbywIe5FwSqaQzgu/nvavZdgDNynowEKssTWg5s6veLRl0dIkMf4p2lj5KBXSrdcz0hnIxuNm/rR5zm/iMg5lk08QKxcsL/o3+bfYC3U8sbdXzgSCHQ22SlAyZJZUvPViL1+FCxWd4cYsGMHC729dVBxF1axK0q/yeKM27TZEtlpTx4mJiY1++Yr1/ki7JoULp/93hW08hWwmvZ6eOh/a7riNgzo7oHFbVZXNYVIKDK6dfnazQCPsUEYCaO87hG5oGBMt0CfPmoF4LGQzMR4So6M0nGnLZp/KT75LV7AxUZ3Ns21apyjZOGrd8SHNwstRgz1xY3uv457aZCJV428T/+jai3C3Sg1aZ0V19iXSaAlvrYD/6VcPJIDMhSX+7tobJ98gbHW7AyJc4fH0Hh/hEex0NIHcEFlDtcbD0sahWnKf9MfFWdSI+y9//hCBNTbUuWSENZcuRyvVhEkQOYRaszEpyoJeuAzf0FJUJcMoD53VYRj550EIcGvjRvgkCryLSvRVNViWI4tGMm2QvzBAvMOz0eESITNc93eY0VaCtSr0s+m3uFBteYarWiH/uS+L8aYOgl1nUu+9fGVcrVg3PH5CThNkHJ3rGMSlxkuteCWr1jg6COnswfjH/rNx56cQMVut2JVt8SnRx3SqD7qxHPEOzeUM43VVd/RzMq+QLfjL2BHOxhVZNPC0OZf15a2KzCC97zMHkcHgM4wtuZAzG5Y846ebgNI1PSIlJL0UeeYJtBx
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: glance-db-user
    type: Opaque
