---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: heat-rabbitmq-admin
spec:
  encryptedData:
    RABBITMQ_CONNECTION: AgBPlfGzEvA9OJ0PX/sGZSpNFJQPaoB50mOTku9MBzv0Rk5NvD4c/fR9qdxcwvKxH2E0RGYygH+7NBmoM0Rh9hPf3wmDmZEHK1UlHcViJOiaOcGBOX2RfJs8u5o3KMlgfC7qKJem9QHkaf5tkZjOCvXTiTfHZEigX/LozUeCiiqyPknhkaAwWEVRNZQ7UM5LddPuVndpxfV9T0eYfS/39Sa87ziU7gc/m4yoNYOJORIWTAoysPXYafZi9if8Z5GNF0ZgDHRys3wyrQRmOIeIS/vJojzvquSDFpjOx4r6tNbaaPl8wfPWQyAHBL3RMKzCGto+43TVafqGPjQ2sBxPfmShzk6kKLMZRDrmRlMZfURge6SSayDlTHZ4pqFzGyBm1pQavZXTxTi8GH4j5gYFL9RB5O178wQI7H97TcYsdUdQ0YfqhZ95lOHJH+j+771UDtQO5Qn9TUUu77qT6WOjch1ZcZ0mbTgPhtN5gGNU6zsRwAuabcTkC9Zrgh+zuV5BXiI/ETlvt7xMyuDeISw6GohVl6hhQRS+z3C2wUJDNGCvo6Ef5Pdv3/geXRR36UlrBC30OceVzNXcURU5W95GDKCZEgRHlLTIFGq+cnGU+OYSicEPc1oRL3cptTHxzqXkgE8Va5EyJ/BPBQ6AbFa8xMxhvkWNRHbAmVxH2AyME/H90KPblqXe9PrG7zMZQI+3J6uFJXl1CJJM1MDfTqgpUec6rr1Y/oByIcdaDmnjHLJV03L6l9VGYJRvmgMcyaulMw/HxWpBKYnBMO58rV3LDz83sJnnpMaz0mBEvwWDc9mjh3xTC2FmnZfYOXzVX+R9orjBM8HSUzp7RQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: heat-rabbitmq-admin
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: heat-rabbitmq-user
spec:
  encryptedData:
    RABBITMQ_CONNECTION: AgBG3aQup6We9zZN0rZzcVBwFIwlh9prvc4ryz1UKQ8K4R7A2j/SsagTLPAJ+n1x18k0jSH+PXeHfbWphr2EjeHZJHkv+AFhX5+tDaTZfmSlBkAnIVHyVoUBpGnGpQ7D/xccVTWXOLPWyUP5u8r2xj+rl8cD/Ikne04Z318+MI7AKaev9HzIN6N7VDzFs1tiQ8SbRLgu73lN0nvtR+6wWrgZpFUykhZQkgcZFb0NMWUtijl5qz4QmXyjrRYcSb3XzRC/CLB8IXr7bsst/MpVE8XGkGU1qvG2Uh0V1BNc9a4AIxR+jPIQCvXSCYsmC1OBPtlTyIs9CqaIVbke9VGFXKAWvooNoCVl+VMr5htJ/wkI8GH8vHhnSzVZfJki5At58gZkv7BAF+b/Ad1FIqjAXGFsnsgUhECIZ38QH95iqrt/RC6UdyVuB3satmn8D/SCUztjT/qywrNgDcga9SAS/btO83WUEyCtJ82ehAd4MhIKOjaGly6mVUP3VVwN2m5INwIpHIKsZKI2UfovEw0ExA5PRUwpxxzjw3ZaMyCrtXLYDXt+8QvHzu12bNbuRv8oCNFuiBSFRTaQrqLD8Y44rHi8nyuLv9Wm4jkwSEtrPOODFilsv294xHN1gQd37T19vmflAmAPxNUNNK45uvHAXHf+s+v/w4IvGNj2Yn78LKEgwj+pUOuuXz1BBaTfhNoZfHRo4N8cu/ZHkMXapqoawtAjnlVlIQXkrwnc+aXPn5JZtMtT+F6kZdrL5YExtgT3ocy9o9b+eAm8BlLJnTi5HWchC8Ny/a62R7nndnhlUiQr83jy1OL4ig9UToidPIdfXCxVfaxZKEPut5O0dx/95kn6RK7/Re0dyiS4kjKV9MFLzrxmVeE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: heat-rabbitmq-user
    type: Opaque
