---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: heat-db-admin
spec:
  encryptedData:
    DB_CONNECTION: AgCtXhmkK2+eUJkFvDGm6i8c0qhpKCLfRRBMLXLOuiER2HeGdG31gqNb52Ez1v1Fva6xa7LJVzYH1US09kaBArd9EdUPhzU++iuDPI8ENzcQcUjgmPRERx8RvQo8uaBNcDDesjQxJ/xFkHsV9tGxOKPT9pHhH6dGeMPLCt3KP5AbNQ8sOIRR66LKSdu+GyFXx7aLXt0pir6z893ytg5oJ6pgGSGViGFIgHSloD+E20XW24WQ+u8YmPPIipixWwMCFwQpuKa3XFMj02EThTS3Mj9eAmE0RHLkMF6tfgjWVVD70wSPo54eSw1gIyEPI5xhHEaZ+lonDkXGbCTFNkdlAAq91IssQui6FeAmKAigc7ill8sJyEM/GDR0yEzYca3/NiPWfSpHrRm2zTEhW26e4PoTz0FBRvebGrAejqVRiDt0Ch0iDJKXhdPNX7/m6EeKhfl+vi020kh1lXn/sIR++bdTZzz5rtcSHWddQnieFR4622HpGgXx7sL7zyuiijbf1X3aDa1kn/9KI+mVKTCTL5ZA7uVl72tRsA2hHNCEETXRsibtrzW253Hfh3KhmCYtjd83Jf9rXlUm0nqdNEGXZnOFLHmB+ED+5t/HVnbVHRJeiDi6sWKm1cQpca6Q7V42W0PHyF6LTbHCGwQbSomipMXVciTSYOiZcN6RvVaLQRMHFoh12rSiNnlduU2dca/+DUADNcTl8jpqhLvTAanMeh6zoNASebAsaw5jO4CRgsBmyqkVkC8cafub7ffBABuAIrwq9++OV6qTTT9rpKA6MfFt6NwoCs9XwCPvtUnR1dD/08fQXosCNQiGgvU2puhH440sti0CVkUSFc8ejddf6nDhmD0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: heat-db-admin
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: heat-db-user
spec:
  encryptedData:
    DB_CONNECTION: AgBAv0mm9gfPGHicOJ9JR2gHKMRZ+IlCOPlfX2zZDVgRwZ4h739uUWi/BDZXXzuen2QmDg4y+cX6I08qLgVbDdw82uQiVCyiv61x7fgvQ7MVTgN3DJT8WOit6cyaPKOWcJI/tQY9KoGVtVBuVJ1xuvLOazBvKZSJlNlGmCI7sY0cvdhq0aWBHD8DHgF2eNVSU7QyaIxOZ8R8k589CfnnK25t85ezLiCi8QVXt9fLghOjSgvbSJiM8s6uXpSdzw8DcP8Ovz7TGpTENjoOchDsXcWPskBbcfE5j7cqQMaAifKrhNzDpyGnwpDxHWcDyCHs9PrISHmY1LTC1ZeCvLb9KOvUrsE+WmCktqmBseTbN95RsSeo53asFxx1ZG5MAKGy4PbSPAfxISRgEETdGXNIjP6VgmmFMPEnGZVIbstnixa1xxl15tK919Dkrn2/m4VW3eNZMpWZsq33FL9RUG3GEBSScE3MOB8WZSqMcWkGQN5D0IL9BH9UOtvIjZyOoXj1nRy0cXvTP5pWIcqcbuOFH8AOom1qTMTMF4sUpN/m4kGwNuNqw1VKSQiH4H2ZpRRqzKAS+ktFo9JzrcJ3HMrr9tfcYTZi9ORh/dfTb929BZn0Gq9U9lyiQtdb7H63+u7K2/yxTHbA5fIQgYdLLu5K/e2iRA2aTi0COBJDVR4rhyg9GVKXw+ghV5IOllbsjLawriKSRWJUviCr5Wy+OqHszYq1EDofgtblW6Mmt0A/dkigSDjun/DkUcd/oVTqfskO9gx/W4nwl1o0hLYpEounF7grP+asKxlnzjWP5rEPpSxMBphudaK4bYfkn5wpYyN2lNQJ8u2MkPwpULlg5KrTl/FbUUY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: heat-db-user
    type: Opaque
