---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgBs7Pb6v4lZpmSXtKTzMSnjYN0N7oLMvq7Okaly8euK2bs9ihaVHEegrWbBMnDm++J4FU6fBZKPsK+mRfLkLe2+B1QcEWx/OYk/ayFmTjLxDL/ePvAmfxS3xZnM+kKZc1OsRIsa2Wy4vy2a48OriWL5CEYYf6tXCjqNOQtPIgUpvDqzBEa2MTQAKt1bp5GfgVmsn/mQPFzNnuA1mroIxIdsmRMNtjW3hrafNLC2x0vM/YTq/t2XY+Eel8cJdTW76wsM2Qqz42jeFJwZ005QtPMkSN1q1syVL5ja4VCL6mjojr8yQziiUzmZFvuyB0TUzdJdhfEXWcOZOmoQ46lrypSYocfUyESv7CX1kRVndSspy75l4XQy1nTGe+s3qaYilyNnnRFADZvjFLHCVTc82SUSzhZDqHrVs/KahaIDDOVJIl9TRcyEyqO/UIJQUVNuFpgggV7bdoN7W5HyXqn4fOD83z5gjOWUQPwbOxgwlMgpTL+9BgkDeIM1OrJbrzSchW1Z0BD5gwy3VyVDCjgK8QLy6g3hZSLknuegHKSSM5bGzWyd7d6z01OFo9eQAmLL+wnoOcJYw1CqLE0WBgqAvz1IzGELFQ6ajenUbnzIg5g+yNLzrM82u9XMcT+ZYVvBKJsgOVJWTDCqBgPpsHKCx8coCKUjLlAHVwcYkczdT7oaT78McWayIyfgWfBsA8HcRYJbJTbfHFMyI8GTl4wPkgSmymFwk97e1qqEoGsJID3yGg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-admin
      namespace: openstack
    type: Opaque
