---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgClZA0rydNAVVnTOcx6Sp3/iUjWxby9KDxVp+Ybglwx6DD2MDFabIfbGTjOmNISnyVUSn7GK25quR5t983vYsru+l7FL4WXxhg6GA1yt64S1MtLLQfZawoGO4nbSdhegyeaXFzEFEGeKS1SD+5lP8IgJj3IXu+oWrFzQ+gwrCmyxGo5n/FGqf6bZTBF4L6pNWl3Q5mtPfubH4N0llij/w53Z0IgiNKs68faUnrNjQups5elZgXc7i3NOGdhux1TJGVicQVYYgfg9f7trVNzrQXmBtfuzjGWqO1uh+u4xDDjmm2sda4d4OfO3P+Igu+lZN0aHN+JJLAMN68JRVXQw4wNI9gFZZeXLWPHrKBRXO8WGQslEgpB8bYfYO74tkpRstgJiwgOfqSsMY4E9CgzPErLo6oVY1GLZ8om18PAPC1xVFwSozkNepihYGMQdjVPXXtqfj7y8a1p40ZM24keyg8HN7jk8xwMjtYcOOdR/YDhRw81O/Vi3ZAiq9t4eNB5dD55sXYn1WEJ6aKfZ6bZ4WelyuHZ+UAeupOlMS67ieW8PyjoF9zBcB+4RpUINaN7B9KiRyNvw6JJUmRsh1byUGUBObiqR4kiFQyUuXeh0YWYXrdQdKNcbrVfmmezCN9eK+I67xzWrtgESNflfa3p+grwFiUxQpFwoVcvfN4Nykjc2HucgqzaD9koZJcbGCOi5x04YtXc7bhLF37vC4jBbvsgG8T3crf/F7AAgpZoRSppRkpxOPoyb70MCaN0MClhl1X59blpS+2py003cCdlsP2R
    username: AgCzQcbm6lL+UTWvd1MLhOQ9Vk8ByiE890emgS2nkAb4a4QwMTT+Y+HhsBh0+xFpbp040037aeUkGVCJedRsqcFIVhcJLu10Ktq0LVWxIlLy2xP/aHza7oU8Izc+V6yPglpQ4UUu/ydtV/zmTcmdsFJ5LA1g+rueN7WzlZYKWJ7t1tY3otkp0/Y22/iDORylDRcHy625IBSLqvGaKzF5kCfJvcAwdl6gWJ+UXNY5VdivC6SmTWgm/wH/ugDcrmD3eIwT4kxnSxy4lHhs3Np00Hs0IqK6LWYUT8mJz0oyWS/t4lNnJYky0UaUxJOp7FMUcJpy+oX1sqBxc/hS6+UdANJ4QySBIrC1VLX0Yv7Tm1CiWW2WKuFe0IZMBHG0M/5BPmalJup3ctehs3G0MLE9Vl8Z0aHplZ7KgmuflBfM59d3diJEngE5P5PgkCcUYSn9OpZFsRvnubyvVLhlFn9am34R9LvnNIx9/4dJhajxnjYFdy2g0gw0gQUpIRBCl1tP+g3tzwWbt0AAVvYxOylQYFR4iVD56j+PXG7y+q8xqMxFTn9n1mHZhJNVkpEYnQKfR4LvP1efD6Ycasb7V6QmaSqAyyFxntddZroEc+GyTkVUr77i/bTRFfMtrUZa68umlf8VsnMTDlIcgR5RHlyeqXL031aezbdWokYUS6pWG88mQAuo19OjakSUZ8AjAwg7y+ykOVRnArQg1w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-rabbitmq-password
      namespace: openstack
    type: Opaque
