---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgAzzWVEsaUN2t1mtrmhPCY3/m5xsPwrV781blB4NzaMCqN4TcR5rsuIxeEikuaRw+Ig4nDrG2FDr8bgoGP+SDhmI+a6t5lu4Bm1HE0l6jDOuUYHwcCZQ800n6yvRalmQfrxfBxMo7+xqfXvE7tImnPYgPIAu0cRQtkjz+TD4c4xx7LxK0Sp7SZnW1JCQCvlanWI2Nt9GJBaO3UQKm0cqmKQ9juhyxenlgmIV79cZaKLn7n7TDPTzdJV8qle1YJtsqYV6ZRHOZvhuGwitve6ohDrKb4yfkCwgWlDRn3tO8wDYRqE9FoFxGr+iqI+4noxEN96lOynfXiFFHFo4KRgtNfzASkVhpIrwev6YvXYpfGkNaiQQeoa5xMrgBX89FRqbTauMTM5VWKcTdSaiWb5Z5dJwTqDMAYfz10tKSJPY5CrTYrJa4+wgoAwzkpu4Agn4KnZOFVJZemJyAk0Xqd7TfIsvg87qeSP5zR/0WBIOroWpWSyNFfAqAIa+RJkKS5hnPFRQWK0iPLRb8N6zoU0PsI4MQ7zJMsSkheNjyI3Dce6NU0z/XLbbPkhdnP4shBjTJjB/CQoDu7yEDHddzZqzr+ovVZ4//J+1kZptY6WXUeAejiDnHVcnQ374XX75RLxMUTdVE805tIToJeJ9/KiPBKIBMMR3n2025PQpHAeJLxfo2s1xJ8OGxB/LMAcvaf/vaNNLNiJXmft8kRZ+t3piFpR7mBI1d+smUFdNF3RvdLDfQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-db-password
      namespace: openstack
    type: Opaque
