---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-credential-keys
  namespace: openstack
spec:
  encryptedData:
    password: AgBHZR1bjnT4vUQUxhp+3a5poFbVlY5mx6qcEhqAzLac95sEWqORHrhlwCzkB0Wimsu9yqa6GdTHT7BWzL/XeCsN9HimjN0y546YsRm9LIkVZu0JGBF5Xj+MhgxMXLFW5gEx0mqDF3rULO8PNjoqbS6201sgSLwOjsYq0K36ZBRkCtJGh0SNxxsed2zN/6adtQdKadJkOq6pRE+fhAUNh89uQaH1+4vBYEBXM+vMtl7EmGlkarn1nIQP7e1wgYQ9CM/Ckz+TwdyDoiPQNgPcZK+PuCppKlr0aKPKOgDh75/XjT5sHTnftPa3dg5hWLuAj3G4X1lSQPc9FH1fBN1TokzhkGNnDOKfBMcudzFwRebSaIkA/22vQvC0EPDM/Vr7ya3OSqhw7zAMrDEGLqatmH8DgRETQxhIYOHlf7XPbt7ZQCO5NzW73EEuBEgmUVJba46cGZSWdcqKMKkkE46cSpUfyH3boPVjhvepwGdgwuJ0Xjig1VURlLbdJR8bKWiJNxEfdnO4Rd/q8usrOtAadFK/isdj4xu1QIexXuF7YGeg1DycWHolm4yaeePtsWXInUc4LuzY0nWrwg3axTg2fBvO49T2BD37hYnrwYGucp0YA6V4xTA0IhxgmFvG3oE1EXBxKep3mwA1jb95IuPZwCwlGd1pJnQAccGTUsR//fuRaYwQ5eEINpk6n9ogTbK2DPpS46t5JYusE+QqA7ZltrRMrFvqR2RLMD38rkNHZde3qQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-credential-keys
      namespace: openstack
    type: Opaque
