apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- encrypted-keystone-admin-secret.yaml
- encrypted-keystone-credential-keys-secret.yaml
- encrypted-keystone-db-password-secret.yaml
- encrypted-keystone-rabbitmq-password-secret.yaml
namespace: openstack
