---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: nova-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgCR/LNdVxrOxqe3i+C4htlOqDQFsn/dYvIn6Azq4B6dOdaLiLtGwRIipfzSuBN/n2EHM4YS3IagyCt5WGGUtSkK167/OYEPnSo/jqnrSWbAd7hiOInpOfLvsHfQSXJhhQeLaDHEXjn9P9WeQ807cZDmjxtnOV2wGG2406j7ZZ6yZpsSEoo6XlHh9DknxAu0BqB35S9ppaROJN2F6CmDtlN5OxfjjKBTopY3Ede62ofEFaoxRzNzvGMqI4cvV411lL/qYWFkzTZtcPV8JKKt8yZrwMB0A7esozMYazuQCm/LEUFJgbgIouxePe2ajAzhfb1edBD7s4DifkAqnxj9bwwOU46OgVReXAm1oQgEKXYfPf8K1pCVprKE8xCu5LRTt7KDZndx/zD+DogXXB5/+QQUtq8vIgiWED3v7pNeAjJkBUZACgOAwaInN0K0d0qaKFesAQkpX99zkdb4NikKPE19hknftQEiWJBF1zATwbGhyWECTczE7aZZcvNlYormh9LPmV93OY/Pw2/fcLqZpOItA8HULGB5eEhpwoJK/BHtipc/fvPlztYRz6YFB7zxjtJxxBXWoQ3wH7r9XLBvnPobs23m2dXDl4/hxJVAYKxpriHSGymdWdO2dZOoEN86xahvSfCgSrsh5CZQ17HkaaRLccZ57RCkzdakhrIa/Z/19qHg+TwgBKqQZtbL49jIHjsn8LF1YGQ0M5xfSy2mKbE7fSpCgEjY8h488wAzREds3tIWYihFBElFwYDV2xy5lSGxmqmxcB6cld5eHEUK2UK7
    username: AgCz6HD6a8efmdLiHNEziU1nCyBJtMFgpaMwZQMSfe6CBb33U4lDyPKsdPhN7Znb161qNeA+CydGsEI8C86UE+TkS5KedGny5Ke8XZSeeeya0WXm7xgBXeuhO7vSuJ++8AL7n84arD2bcCTSnuYrzAdwJyC66p3gEC3C6hRaMEmIAnbqVSkyl4ZEcytOhemmACPoXCe8GAi4f+RgE+e2FqqotUnwKK+eSH4HSNhsPJn4xc+hTwiKRxZLYQ6F+eYfcOxJOJBUl68tgdUeafOZdI+kq+k2XpEtjWn9tzlwIRqNHfyhNoRb8GPxoXgI3C/qo+vFTwKPt4jos6mar0NNeJ4n6OOwGzjQ3E4DrgvO0+HaBFjBOYQL66TEHtV5LlquxAd6947gNXaFl86HsWhAhJZWQJyJnHR47u8C9LHLZIridwNvbm5iqdtb2AI9wEdF5ypfGrRteT31x++hEypvIpFvztB37i/RR8/Ulvm57R/Q/w57Cup1nBHGKXUVMyI1YG0Qoflia9KSmNi0FV1qYPOVq0AtwIYvtpwWvX1+bjdCOiUE3AYNqsj93z4qdjLzC8fEB0A5UU/16h3sBPn99IazF8ql4EGVViLUO9ICYCFsPw8TQSV7TYwhCEHWG7q3YO0xbqvLjixAIEvGFa5rgEu4xEy0LjNh1VlPrqJeOeAvU45OaNls/OBtOp54KJ4cYhTguE+x
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: nova-rabbitmq-password
      namespace: openstack
    type: Opaque
