---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: nova-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgBru6yJTm6H1OREO6SMe6j21egSin5peQ2kgP0ovZpwjThUcjdyQQqdzBxfuL4xuX00eR1NwTplt1MmKJ7hO9aRBtZ9OhVySNicZ/w6J1jdzHCbrrzCL5iI6ViziGEnnsLS129+QopF3R4siLom7MwIks4TzMSGoM549VHGz85HuyMtxcivYduNytXvBbD03v7j/whAMOj6diFGWxc0uOF58QmCsLUegkanzLvTKSN+YnswaJvLBY7D+bQSaUVuIq/v97rCQIoTL+q1S+MoAhIVN+CTrjpfMt7KAJM7riaOrarWpqSJVvJ+CXbBPs/J2y/KFCjTl8+y8J9U66GWPJ3O8RByFAtZTMmJYbeLnxhh0gXzA9WYdEUb88RfFCYBLWfpvNSK3EwiIS9XyYrj8YgnhpmteGd4bSqXQkrkxCTWBx3bMULpfBr1aTzdo5excNECk4ITs3MwokQzAURkj078t8vD14xIskpPMwi1LCe2RYmxzY2gd0dqFAUDnCg6Rnqjch5FejT8eGnSY4YWAwc5OkGwpJXnv1+Ta72MQiDxezoykNFDsQO4LYVCjFAVAV8GIWb/tY28RzCj7h+opVbHu3VhvL2ihdjHXGe6O29yLzkqnJqOdT6vO9TBH/aUU/WgFaExKVeDiUNus9S8ZjNdI9PL8vf3Zi9PfXEK6diutnRn8djPUH7tzAQq3djl5EDsD9E5WBh008gc6FtTveVO1bN9gc7vHOvTt9C76sziPQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: nova-admin
      namespace: openstack
    type: Opaque
