---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: nova-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgCcVH2Q4sBQvaUt6jCKoFkdD9CjkCKnADjH7s3ecZrqdA0+fbunlVUz+xjJ/1dRvhzJ52T8w350tN3Xy+Apz5eO5OYpDbK3eYeYgRSpnvZXM6lf49Y0JpWA7iaqxIkwNWifughmtDtzhALCKtcx4JPeKYqaPzoI5gISNDy7LR2XkOEftSfInDlxndg6acJFPzXH8MHXXbRRhzyhQUfxq0nzIXy2t+x3Z+jQane77KXPl1H1mIVfHT7edJUOuYwof7VDT2PoFjPE2vQasGTeHCO5Sjkg/EkvdCI1ejVi1LB7LUanvUyOUcvd25ttBxKjiYzUdyn+GconWL3EJSzYQL9kSKSrgD8279pgTaNMfQVqng8H0cXaK6BqbL+ZXEipjdnirdfrdhgubeEyN3L4jt5IrfPjfCvujyTS7APKf7nDH6b1vBjT++1Cw3TaGjE2fgnLKhpBTXODuXyb1gEjBmsMoP45o6MIhDmxWTt+oIRHxU0dqLD9y4PnS8A1OPND0r8Um2DKWeuBwg03HCNlPGRhLZutyvI/N4b4NV3L84jIg2/Fg1fXVzooNZ1JVYw4bH7atOpthXaVgiTxsXYup318t9+S+bfjP0HtS3e7oJuhR5RF3iMDlHIMbded8cW87PaRBZo5jpewGp0dske9nxum64Fl1c17cq3zHuOhQE+GkiN9osSXWxoe0hcsp4reYKTYe3CeCD/fHZB5uPl4riXEFLKbkXJ2jNzIuV1spQjdEA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: nova-db-password
      namespace: openstack
    type: Opaque
