---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: octavia-db-admin
spec:
  encryptedData:
    DB_CONNECTION: AgC9eX+ro2DIIRaiJlBZBbJN1fW6WG5Vts/32YoWbipslKkeckokPxvEGZu9B95n1gWWO8jhoFpvaJPp1NdryIbgaqyHBnxEKkeWmyDWgF89P52xJOIZWfxlzCZAUCzbKoOCAN1vmdT1RKedluXz4TNOtHSOr5P70Qsal3+435EGm6YtGnyHc0rW7nt8EqOuZbPByhorCrWJkIf36nxHVryOmwqjzlGePSavKsKx0atOhmQTaqMYyDJS4pjDYOFOqtsPkyvlrymWvRE4zYGB3sZFAOPP2iAsGLE3SZ6fHz12NRJ6XHdUu/ch5vK5LucX7h/pRnK3/ZZ7mpSA0hiEhHrWGp5qs/UOmFMnyMSWKvmt3lhtyJLP4tQpM6dS9dIdiaWdaWat9YuKGtHgCAGy/18zXIPjPsvQKN/0x4tY3/7FuXI1hkhyHlwftPqyi5Lta3kkwqoKsCJgzQXQNqq5Gi9usvRPDyJlJ2xPdvlUWSeXpaDuCL27zAOQd/rFwX2cHOedD0kjHgFYkVGFA3qgQR0ZLKCIaZ0c5SGnj6CFxWAfpKvN8Ql2B4wZw942an8+8zv2sJEQ7Jt4PEUsaKmU858hQh27taLCt3zMpC6x3uWeNKzUoitkmBmsc3N0TITjVU05BfYVVhvAAUc7ft0AcqT7GoB16QOejz613uME/2eiiLqSYIfuDHLu6AE9yh5aKU+J+csGHDuEzzgfecIb0bVXEvnRSvUhW5+Jsxs/MhnbdIXQAC5a5cGiYxx8PHzhhm18RB2guEpeTu9oV3V2icZzqUtrt4iCurl1SDy7GDeSDPxvIx/GNpz5dOn4rHiBEJRn7LivP3OcDJmUl4KuJNFMdy96gsk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: octavia-db-admin
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: octavia-db-user
spec:
  encryptedData:
    DB_CONNECTION: AgC58IPnivVrwZQDcTFNAcy0XwXSJaXsDOecLTebpuafHJNm7Yz308aPQ+EYZke7cWUE6fK8gCv5lFasOOPXLaBSkZNDer8ABkH6BRk+b7prZ4jSjz2BamPCYUXP+jGAzrmwOo6Yx1IbJUNzjyQEtl7MpVXeGpo8ERTkiW+yZVHvDXSmH6YhwAfXom4s45BkbOUw1dzIV39uaGRJSFLGwi5onZgjt22YLs42BqAqV68j3ieRtdBCxklZU5uGv9R6Hknqo/kIqYrkmoCBaervXv092PGMCIghYCSNxVynrN9tQ4KRbYVmzYpT9AeLzsIKT2vftzQzbKhTPQeMFFHFF4SF8yyPuryyMO6BKaUzSiaRHLoXRmR7NKfFjVotvbECwVM4p9SfQ1Jgx3V17KYOuBSpkDa1GrBlfSi4j5CXnh0B2f37S6fQ88U8asfocyMnWlA6JVtstnJGWV4T0j5WXHRothuCMmQ9i3/DV1/1e7YNBP9f1OPdyhaRfcGMqdTU6w/KbG6fQg6eT4gKBtH363T2eEXAgcHeks7dbLCNO8+gL9uuxh7ARMyJY+vZhNHC8773npCDNlxSlMTNqt74Zh0XEvmuy9GoRt1jPng9u52ucIrH6JuoiSL3svqunuyaoxHF2G5WHCTnroO4bXtGcbXpEcywc41XlQzIpztl73N0WyS8o79fFI4vbtekL78fIgWkq/f7QdY6vcEj9/vBrnluXHvZvIVv2FMc10WjWYwjYMa1YF/W1MyBEAp0flS0AzjGfX9hM29lgnaXThUTwU18Nwqjdv1OuwWMOf7+dlKcGa9Sw66Ruk/pMNXjRz3rEjRrE716B6qKE8lsOvxQqAAiM1gatziZAfM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: octavia-db-user
    type: Opaque
