apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: openstack
spec:
  replicas: 3
  resources:
    requests:
      cpu: '4'
      memory: 4Gi  # This should be changed to 10Gi for production
    limits:
      cpu: '4'
      memory: 4Gi  # This should be changed to 10Gi for production
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
    additionalPlugins:
      - rabbitmq_mqtt
      - rabbitmq_stomp
      - rabbitmq_stream
      - rabbitmq_web_mqtt
      - rabbitmq_web_stomp
  persistence:
    storageClassName: general  # This should be changed to an ssd for production
    storage: "50Gi"  # This should be changed to 500Gi for production
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: openstack-control-plane
                operator: In
                values:
                  - enabled
    # podAntiAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #   - labelSelector:
    #       matchExpressions:
    #         - key: app.kubernetes.io/name
    #           operator: In
    #           values:
    #           - rabbitmq
    #     topologyKey: kubernetes.io/hostname
  override:
#    service:
#      spec:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: "topology.kubernetes.io/zone"
              whenUnsatisfiable: ScheduleAnyway  # This should be changed to DoNotSchedule for production
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: openstack
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rabbitmq-disruption-budget
  namespace: openstack
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openstack
