---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: rbd-client1
  namespace: openstack
spec:
  encryptedData:
    key: AgB+f5mvvW1hMJm9zQQGZCbx7BZiCGUaU1+B9Yiz03CiTlTrv3iQi41YTsA7K772slc7ZWLtjkCejf+N/a/x5m/kTcmsIV4kNzLql79QddyoZOz/KQ8ejK4Wq1aswyikWvRlhb/hKebjcsIptliPoksDN0jFagGizZTN0cYVKAPoYQdsvZzyg52lINUjiKVkOrA9/XJZd9wjJ+cah2IlvLC0FOhAm4uUWxvWxWc4HpOJBzhByEKcVEFo/GsLYi0E2lvPlZxq9dYTQoHc1DqledoufDFtH3fgYJ4r+2/NErDhKdXZFR2eN00X4ZpwTDi1fkw/AcPOYxHmhgg+3Pew/ziBR7g4P6fFx4HCGFLVMsUFpPDd8ZeObfRmIDi81N65rM/yRP4DZuAGJZmsPwY8PEZg8PD5qdDpSMKT2PShU5r7taXISXN8cu1NNUbnN0e6twGjkkk5Z+GQneiBKihY+G0igiJJbuXsJ272IPZO9d4gmCNvfdShFLXtJVxn0NpmfB39K8+/CKVU9uzC9L26Acf2K+7LnfvJUo5dtUJNdYiN5L8xkHJpMKAQ5yrM4xuqFqZMxtHaYqoylDP9EYv18w5/MSZh4ExFsTOGAt5gAyjTPy3QmlDgRLSvd2kCpeRC1L3c4qcUzE382MC6Fh9V07n8dUWEYWMOJY2YhZumGWDwFR7sOHon+qdG9M/Mckb02URUFxW6yZyUwY9KMinyVKRfpyIHNTs5uAxsdn5oWKyTufvy/+GBCQxN
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: rbd-client1
      namespace: openstack
    type: kubernetes.io/rook
