apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cinder-scheduler
  namespace: openstack
spec:
  maxReplicas: 7
  minReplicas: 2
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cinder-scheduler
