apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- addon_manifests
- manifests/placement/templates/configmap-bin.yaml
- manifests/placement/templates/deployment.yaml
- manifests/placement/templates/encrypted-configmap-etc.yaml
- manifests/placement/templates/encrypted-secret-db.yaml
- manifests/placement/templates/encrypted-secret-keystone.yaml
- manifests/placement/templates/ingress.yaml
- manifests/placement/templates/job-db-sync.yaml
- manifests/placement/templates/job-ks-endpoints.yaml
- manifests/placement/templates/job-ks-service.yaml
- manifests/placement/templates/job-ks-user.yaml
- manifests/placement/templates/pdb.yaml
- manifests/placement/templates/service-ingress.yaml
- manifests/placement/templates/service.yaml
namespace: openstack
patches:
- target:
    kind: Job
    name: placement-db-sync
  patch: |-
    - op: remove
      path: /metadata/annotations
- target:
    kind: Job
    name: placement-ks-service
  patch: |-
    - op: remove
      path: /metadata/annotations
- target:
    kind: Job
    name: placement-ks-user
  patch: |-
    - op: remove
      path: /metadata/annotations
- target:
    kind: Job
    name: placement-ks-endpoints
  patch: |-
    - op: remove
      path: /metadata/annotations
- target:
    kind: Deployment
    name: placement-api
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: placement-api
    spec:
      replicas: null
