---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cinder-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgCoQuLMbHCgq8l5unGnAU+9p91Hun47cOkrTgZLHL3PJshXYMjboEQ0Dd5mUArFK9YgUfG4vkoxehI0nRA8f6w6NAba+p+UaHotIdJ7DEcUexwyGq7QJF24fqmooa3ZJ+Ds+9Yog1MFPlqpKfd/D745H/TZPs85DcOwlwvrOzt4VYg8eBZRRpbZpR02GqHkD3R66ZjS57fsbaVM6L3uVuiVu3n86fC1z/FpDnHjSzm1OtDZHSa0UXENxLHuM4bjzmNumjslt2+Q92QcP+1JtgCEzD9TuQgtSsw1VsGVb3uwBrhoBtS2yFZT22FDzc82gU3jiMXmY4qEQpXo5VCm7JkLc+2rRpOF5JxlEp8z1VRVq7yQmgeuoSGjTcGN+L5VRRIgrbwIvBcD5IPZ+n56Wl8TuR5azdaDtuZ03JwwcL/kaCeL5JHgBp2toF2coR3Aq7r5aYQrTO6QYjkN/cP14cY5olnIGQaBjK5LdJrxBIBTHTF4Ta2WhPPd4mCXDhOGPWEoN2MBv0664SX6t6mqk+yDAKZwUJyoxahggoK6xP1/Zcepom4usue8I5ZqUcfo45U8QYN1rlZbA41ccqP8PyRKxdHjarjcmP3d3Axj3BGowkaAxPkf2YlRSZL35AMQieaAR3YUVdcz6n9m8375IrvJREsUjuL/2vnQgEfu5uxwFVNe8qcsuXjMO7N4cgoenq47OBlgM07fzL+wMMxOCAN/obcAgZDj7lTSGgt3pInl+g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cinder-db-password
      namespace: openstack
    type: Opaque
