---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cinder-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgA9ed4jQVOZych/enS7EPVBOEqqvj6oooZ6pZ0a4oRmIj8jxzRGxtHbUOsND2cmWXttgd7t8E8gz1z0M0bhmBPZ/xcAxEt+H6E/OL+Habzmfzm7XAZPnwWg3YXCcPwat5y6PP75sBRq2Kc1vOIVx2Uu3RNULYqNfrrS0R0PAN+9NoTziQ0xxEj83ycqJosK6GfBHTHrZNrQ8uH5GRtB+Mj7MmhYOS+8zp3cdqgKP6xltTVRgvLKSj0ArhyzX1D2Zt4BdkTZ0PEwhduCo8ZINsaFId68ZRWVLpPl2chMJ0qTqhH0hRRB9ueUD0VDGS5jqOWA/KGOjD4KguJaj62y5Dc167usmV0rwUKvAwHtHT36xl+ZFRM07hLXpnK9ug2bJyFIe6O5wL8IS61GS7SntbzQ0b7cDd5bosBLKr57H22UJX4LuZ/2h1bpE3D6flz4awIx+5+cLHnrzapfCq2FCHdFqVUyLgXxkubNmNgnSnNgjZQlvyvcliZwbcKoEBh+DvqFKbN5T+08lSCuMqKmGHY0UIRWH1JZYhh+1meEdMuJ5r2CoRkAHlNJLoF+p78z4xpjQ8q7k7OoaelGY4MVw1JM2m/ZAcKJhnV4XzhiNYNmGkSEr3JtHwLTzjDfpNywa1ZmreABPeUmVqK6sWHOaXQnsplPT1NTH6b98jeFu9Buxc96Fs0nCP6ufTX1X372CflxL5Tjf5IgVyKcxgHa1aA4WkmOrFAY+NNVpNUWAAQsZRcziR2peP5Va8LtVwBRXcKyfQNjT1YLK52IX5s9Pv3x
    username: AgA2g7WeaMduqXk9LWFnNJZd6FEO7QZJRNwf65TcgOI94I0bj+8iOtF9BdPpkjJwb1+jYELAxV4pxoO3N1/DVWoWTUzb/6FeOFXCHdc87D+6NZSRSneGHDQ8ng9JFUEq7TD+lUfcCtwKw36YcBPKi6TED9WzSBRuMmwF0XwiLIorkYBMEFSs/5niUgxmMPYAhHYdS+AviXNoiKwnx1NSndl4fdKuFwkwaHtrIlOtLqM60ixuUuEHI9eDIZI9EWg1VRXdV5HuE4+LvHMEIXsTbHND8gJLilt5yHr19yBB8a4bgFft8DvPfvq2ooHNQFKW164rUxnfSbShiMRq5pCpcN1kbWw/V/GHERaEh8LGTU+DDYw1H3l8uPvKkbgh1hqLc5/mYnzNYkOv3bxKgrzljFq0DNaufr3C22oVRPJbiNgdFSmjl5ftk1XMie3wWT+bGnp8jJeMRYLpo3uvkJfmWyxzqbjec70qz9XIFvX10B+ZsIM9O88iWOgwaqlRV3rdkj1O0UjtiC2Q3HIsnVpvNaJ3I1WtiM656GhM5URjsX2f7cV7qjPBMi/ktP0/5wDVkrBMj/WQnfEwEZsv2b0Blzyfg/Iy183ujVcFGsF3v+6hh41TTtIIuAZJAH6YYgxy148nX9CY2uuKSObe3lIU1xnXunVHhGGYd3WeE/xl6gF1KtP9TJnadstCB1GbTfuAwJVEj8yW/ZY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cinder-rabbitmq-password
      namespace: openstack
    type: Opaque
