---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cinder-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgB8VqEKQBbgDWD0hNdk+dPIOwLxSr7aBuxDmXeuJn6w7YLYm11xto4q1+TXikIF/VlKxkms6Ip4DGJp+mthd7kafB64Z6wdXsFIcVCNHQKfLSmWRPKy6KBECanaEytN7bVndQn5AgVKsqgLYvRfzTePwYaryl8n07J7oSASLCmiKhlhBYdCjPcFcQ1Rpit+WcFc7uS3g7AcE1JO3+f4KrEmCpaSJdgXcEroxj2a9bkFZTplKVEKTHsed6a4yYsnLkWjwYvVXs7EsIeEoICBrvRArcZUp+mqHlNEDQzZ0Kad/91Mia/h09tr5nMXVL+Ki/AIk7uWAAr9yVQLjtTIHReEbybJZTSv72RNczKfTAqaxreP9YgAWeSeGFBR9/uMgfzQCjMIcl41fCB+WanBVexDg1s3k0OPbG51/lzAEXfPq0HGH1tbpfgF54LrMG7LQW771ZvyURExV2pI6kJAlKYw0MeTnIwgRgrxjRKI37WKCD/ojz3YGqbKhvYUkByWHp0rTrBkWjjnAakkZax/J4xWxs9U4OeWNmzzxQzgfp7D/d2FmFHJm+OLJplmq7Xx/PwjvzXEU/k4BErelQ47JySRq7Xojh+jAJ+Dpa3gMvEIk2h/rNUpFRVU0/SnhDFENgUnApAdFGo0iBsWNVZESbrH50BX9GocPSxh7nI8g+bydeKLmLF6Qik3OR0HcigWUqvfCZBao7za271nep/YMRmsz6TPtaINqU6aCrbq5Msuzg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cinder-admin
      namespace: openstack
    type: Opaque
