---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: designate-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgCLu+KkdrLF2HMRwGCwx6dbGeUcAdAEvhXkqRQzShhzBdhM4vK+SBZxP6dbd9cqllsqAhnjgn3ApYig1FRNz/ICi02ZwZS5vwFQygxaBZ+O5MZPNX/bdMMUcchZDtq5Tt3xAoWOxTzmBNLmiMmCLZvz+obRA9s8/L4jT11twXlCI97mHj6cA5ne5dqY1aHwW9Bz+4KRmWRlyuxlD/NmvLrauRYOIkNdkskhj3s1O02skIsOxMwbnqYQYLnIPWJomtHJcqPSq9js60F9ac1Lvldl3rZSGdAJp7SYgqbSxORwqUzwWinioIgXDzHHmFJBgv3k7bHOUZVn3Ih8AKG3n4qZnno9TgkCMR4yHzQtRNOEEanQTuWYEhRxngyjiV1Vif6tbVtl6L9E52S/fBKa4C+Db/5dAKLqdKjKWhfPKy7+V7nMideCmDsVvYaaMWQIIzLrE+73oO5M5xqC452BEKt2cbUpzwVlGIMpQwiBPhyCKAT5ZMDpYmlZunIXzBoBOLhYfOB18AhFg06eL/X87CRxjiWzhakeTHzlm1hMhwesaNtUUeVmqrBYuPan2hp6OPJ9PyYsV5Qv1k8HL1JOI7o5NHyUfOhZhXwh9ut7OiH1K+TfXuZW4S1B92WusVoxW5RbdD+klOPl16+SdZdmMKPM4UX8aigONSQneM80nAJIqv40yNAoJ4SghsZHBWruUfRoESVVl8HwNR2q0do4Yz/K9/FhFh9t9L0Mbh0v0lvpoQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: designate-admin
      namespace: openstack
    type: Opaque
